import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "../components/NavBar";
import styles from "../styles/Home.module.css";
import { motion, useAnimation } from "framer-motion";
import { useInView } from "react-intersection-observer";
import { useEffect } from "react";
import AgregarPublicacion from "../components/AgregarPublicacion";
import { useAuth } from "../context/AuthContext";
import { useRouter } from "next/router";
import NavBarResponsive from "../components/NavBarResponsive";
import FooterPage from "../components/FooterPage";

export default function Home() {
  const router = useRouter();
  const { user, logout } = useAuth();
  const { ref, inView } = useInView({
    threshold: 0.1,
  });
  const animation = useAnimation();

  useEffect(() => {
    if (inView) {
      animation.start({
        x: 0,
        transition: {
          type: "spring",
          duration: 1,
          bounce: 0.3,
        },
      });
    }
    if (!inView) {
      animation.start({ x: "-100vw" });
    }
  }, [inView, animation]);

  const handleHide = (e) => {
    var element = document.getElementById("ModalPost");
    if (element.classList.contains("hidden")) {
      element.classList.remove("hidden");
    } else {
      element.classList.add("hidden");
    }
  };

  const handleRedirect = (e) => {
    router.push("/LoginPagina");
  };

  return (
    <>
      <Head>
        <title>Impulso GT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rocket.svg" />
      </Head>
      <NavBarResponsive className="flex"></NavBarResponsive>
      <div>
        <div id="ModalPost" className="hidden">
          <AgregarPublicacion></AgregarPublicacion>
        </div>
        <div className="parent">
          <div className="div1">
            <h1>
              Impulsa tu proyecto a <br></br> otro nivel
            </h1>
          </div>
          <div className="div2">
            <button onClick={user != null ? handleHide : handleRedirect}>
              Publica tu proyecto
            </button>
          </div>
          <div className="div3">
            <Image
              src="/imagepage.jpg"
              alt="Foto de inicio"
              width={490}
              height={550}
              className={"imageInit"}
            ></Image>
          </div>
        </div>
        <div ref={ref} className="funcionamientoDiv mt-24">
          <motion.div
            className=" funcionamiento bg-slate-100 rounded-lg my-3 mx-20 py-4"
            name="comofunciona"
            animate={animation}
            id="DivFuncionamiento"
          >
            <h2 className="text-2xl font-bold mb-4">Cómo funciona</h2>
            <div className="text-justify">
              <p>
                La idea principal del proyecto IMPULSA es que jóvenes
                empresarios guatemaltecos puedan contar con un sitio web para
                postear sus ideas que les permita tener visibilidad en sus
                proyectos, esto en base al Objetivo 9: Construir
                infraestructuras resilientes, promover la industrialización
                sostenible y fomentar la innovación. Se buscaría que los
                visitantes como tu o yo del sitio puedan navegar y descubrir
                proyectos que les llamen la atención e informarse del objetivo y
                plan que se tiene en cada uno, y en caso de querer apoyar ya sea
                intelectualmente o económicamente que puedan disponer de la
                información de contacto.
              </p>
            </div>
          </motion.div>
          <motion.div
            className=" funcionamiento bg-slate-100 rounded-lg my-3 mx-20 py-4"
            name="comofunciona"
            animate={animation}
            id="DivFuncionamiento"
          >
            <h2 className="text-2xl font-bold mb-4">Contexto guatemalteco</h2>
            <div className="text-justify">
              <p>
                Teniendo en cuenta la situacion social guatemalteca, la idea principal
                del proyecto es que jovenes empresarios guatemaltecos puedan contar con un sitio web
                para postear ideas que les permita tener visibilidad y asi mismo apoyo,
                esto en base al objetivo 9: construir infraestructuras resilientes,
                promover la industrialización sostenible y fomentar la innovación. Se
                buscaria que los visitantes del sitio web puedan navegar y descubrir 
                proyectos que les llame la atención e informarse del objetivo y plan que se tiene
                en cada uno, y en caso de querer apoyar, puedan disponer de la informacion de
                contacto del proyecto.
              </p>
            </div>
          </motion.div>
          <motion.div
            className="ObjetivoNoveno bg-slate-100 rounded-lg my-3 md:mx-20 py-4 mb-12"
            name="ObjetivoODS"
            animate={animation}
          >
            <h2 className="text-2xl font-bold mb-4">
              Objetivo noveno de Desarrollo Sostenible{" "}
            </h2>
            <div>
              <p className="text-base">
                Objetivo 9: Construir infraestructuras resilientes, promover la
                industrialización sostenible y fomentar la innovación.
                <br></br>
                <br></br>
                La industrialización inclusiva y sostenible, junto con la
                innovación y la infraestructura, pueden dar rienda suelta a las
                fuerzas económicas dinámicas y competitivas que generan el
                empleo y los ingresos. Estas desempeñan un papel clave a la hora
                de introducir y promover nuevas tecnologías, facilitar el
                comercio internacional y permitir el uso eficiente de los
                recursos.
                <br></br>
                <br></br>
                La innovación y el progreso tecnológico son claves para
                descubrir soluciones duraderas para los desafíos económicos y
                medioambientales, como el aumento de la eficiencia energética y
                de recursos. A nivel mundial, la inversión en investigación y
                desarrollo (I+D), como porcentaje del PIB, aumentó de un 1,5 %
                en el 2000 a un 1,7 % en el 2015, y continuó casi en el mismo
                nivel en el 2017. Sin embargo, en las regiones en desarrollo fue
                inferior al 1 %.
              </p>
            </div>
          </motion.div>

          <motion.div
            className="MetasObjetivo bg-slate-100 rounded-lg my-3 md:mx-20 py-4"
            name="ObjetivoODS"
            animate={animation}
          >
            <h2 className="px-16 py-4 text-2xl font-bold mb-4">
              Metas principales del Objetivo{" "}
            </h2>
            <div>
              <ul>
                <li className="px-16 py-4">
                  Desarrollar infraestructuras fiables, sostenibles, resilientes
                  y de calidad, incluidas infraestructuras regionales y
                  transfronterizas, para apoyar el desarrollo económico y el
                  bienestar humano, haciendo especial hincapié en el acceso
                  asequible y equitativo para todos
                </li>
                <li className="px-16 py-4">
                  Promover una industrialización inclusiva y sostenible y, de
                  aquí a 2030, aumentar significativamente la contribución de la
                  industria al empleo y al producto interno bruto, de acuerdo
                  con las circunstancias nacionales, y duplicar esa contribución
                  en los países menos adelantados.
                </li>
                <li className="px-16 py-4">
                  Aumentar el acceso de las pequeñas industrias y otras
                  empresas, particularmente en los países en desarrollo, a los
                  servicios financieros, incluidos créditos asequibles, y su
                  integración en las cadenas de valor y los mercados.
                </li>
                <li className="px-16 py-4">
                  De aquí a 2030, modernizar la infraestructura y reconvertir
                  las industrias para que sean sostenibles, utilizando los
                  recursos con mayor eficacia y promoviendo la adopción de
                  tecnologías y procesos industriales limpios y ambientalmente
                  racionales, y logrando que todos los países tomen medidas de
                  acuerdo con sus capacidades respectivas.
                </li>
                <li className="px-16 py-4">
                  Aumentar la investigación científica y mejorar la capacidad
                  tecnológica de los sectores industriales de todos los países,
                  en particular los países en desarrollo, entre otras cosas
                  fomentando la innovación y aumentando considerablemente, de
                  aquí a 2030, el número de personas que trabajan en
                  investigación y desarrollo por millón de habitantes y los
                  gastos de los sectores público y privado en investigación y
                  desarrollo.
                </li>
              </ul>
            </div>
          </motion.div>
        </div>
      </div>
      <div>
        <FooterPage></FooterPage>
      </div>
    </>
  );
}
